# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='asr.proto',
  package='smartspeech.recognition.v1',
  syntax='proto3',
  serialized_options=b'\n\004TODOZ\013./;protocol',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tasr.proto\x12\x1asmartspeech.recognition.v1\x1a\x1egoogle/protobuf/duration.proto\"y\n\x12RecognitionRequest\x12\x41\n\x07options\x18\x01 \x01(\x0b\x32..smartspeech.recognition.v1.RecognitionOptionsH\x00\x12\x15\n\x0b\x61udio_chunk\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request\"Z\n\x13RecognitionResponse\x12\x36\n\x06result\x18\x01 \x03(\x0b\x32&.smartspeech.recognition.v1.Hypothesis\x12\x0b\n\x03\x65ou\x18\x02 \x01(\x08\"V\n\x05Hints\x12\r\n\x05words\x18\x01 \x03(\t\x12\x16\n\x0e\x65nable_letters\x18\x02 \x01(\x08\x12&\n\x03\x65ou\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\"\xd9\x03\n\x12RecognitionOptions\x12T\n\x0e\x61udio_encoding\x18\x01 \x01(\x0e\x32<.smartspeech.recognition.v1.RecognitionOptions.AudioEncoding\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x18\n\x10hypotheses_count\x18\x05 \x01(\x05\x12\x30\n\x05hints\x18\x06 \x01(\x0b\x32!.smartspeech.recognition.v1.Hints\x12\x1f\n\x17\x65nable_profanity_filter\x18\x07 \x01(\x08\x12\x1e\n\x16\x65nable_multi_utterance\x18\x08 \x01(\x08\x12\x1e\n\x16\x65nable_partial_results\x18\t \x01(\x08\x12\x34\n\x11no_speech_timeout\x18\n \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x35\n\x12max_speech_timeout\x18\x0b \x01(\x0b\x32\x19.google.protobuf.Duration\",\n\rAudioEncoding\x12\x0c\n\x08RESERVED\x10\x00\x12\r\n\tPCM_S16LE\x10\x01\"\x85\x01\n\nHypothesis\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x17\n\x0fnormalized_text\x18\x02 \x01(\t\x12(\n\x05start\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\x12&\n\x03\x65nd\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration2\x81\x01\n\x0bSmartSpeech\x12r\n\tRecognize\x12..smartspeech.recognition.v1.RecognitionRequest\x1a/.smartspeech.recognition.v1.RecognitionResponse\"\x00(\x01\x30\x01\x42\x13\n\x04TODOZ\x0b./;protocolb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])



_RECOGNITIONOPTIONS_AUDIOENCODING = _descriptor.EnumDescriptor(
  name='AudioEncoding',
  full_name='smartspeech.recognition.v1.RecognitionOptions.AudioEncoding',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESERVED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PCM_S16LE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=806,
  serialized_end=850,
)
_sym_db.RegisterEnumDescriptor(_RECOGNITIONOPTIONS_AUDIOENCODING)


_RECOGNITIONREQUEST = _descriptor.Descriptor(
  name='RecognitionRequest',
  full_name='smartspeech.recognition.v1.RecognitionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='options', full_name='smartspeech.recognition.v1.RecognitionRequest.options', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audio_chunk', full_name='smartspeech.recognition.v1.RecognitionRequest.audio_chunk', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='smartspeech.recognition.v1.RecognitionRequest.request',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=73,
  serialized_end=194,
)


_RECOGNITIONRESPONSE = _descriptor.Descriptor(
  name='RecognitionResponse',
  full_name='smartspeech.recognition.v1.RecognitionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='smartspeech.recognition.v1.RecognitionResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eou', full_name='smartspeech.recognition.v1.RecognitionResponse.eou', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=286,
)


_HINTS = _descriptor.Descriptor(
  name='Hints',
  full_name='smartspeech.recognition.v1.Hints',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='words', full_name='smartspeech.recognition.v1.Hints.words', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_letters', full_name='smartspeech.recognition.v1.Hints.enable_letters', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eou', full_name='smartspeech.recognition.v1.Hints.eou', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=374,
)


_RECOGNITIONOPTIONS = _descriptor.Descriptor(
  name='RecognitionOptions',
  full_name='smartspeech.recognition.v1.RecognitionOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio_encoding', full_name='smartspeech.recognition.v1.RecognitionOptions.audio_encoding', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_rate', full_name='smartspeech.recognition.v1.RecognitionOptions.sample_rate', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='language', full_name='smartspeech.recognition.v1.RecognitionOptions.language', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hypotheses_count', full_name='smartspeech.recognition.v1.RecognitionOptions.hypotheses_count', index=3,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hints', full_name='smartspeech.recognition.v1.RecognitionOptions.hints', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_profanity_filter', full_name='smartspeech.recognition.v1.RecognitionOptions.enable_profanity_filter', index=5,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_multi_utterance', full_name='smartspeech.recognition.v1.RecognitionOptions.enable_multi_utterance', index=6,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_partial_results', full_name='smartspeech.recognition.v1.RecognitionOptions.enable_partial_results', index=7,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='no_speech_timeout', full_name='smartspeech.recognition.v1.RecognitionOptions.no_speech_timeout', index=8,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_speech_timeout', full_name='smartspeech.recognition.v1.RecognitionOptions.max_speech_timeout', index=9,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RECOGNITIONOPTIONS_AUDIOENCODING,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=850,
)


_HYPOTHESIS = _descriptor.Descriptor(
  name='Hypothesis',
  full_name='smartspeech.recognition.v1.Hypothesis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='smartspeech.recognition.v1.Hypothesis.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='normalized_text', full_name='smartspeech.recognition.v1.Hypothesis.normalized_text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start', full_name='smartspeech.recognition.v1.Hypothesis.start', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='smartspeech.recognition.v1.Hypothesis.end', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=853,
  serialized_end=986,
)

_RECOGNITIONREQUEST.fields_by_name['options'].message_type = _RECOGNITIONOPTIONS
_RECOGNITIONREQUEST.oneofs_by_name['request'].fields.append(
  _RECOGNITIONREQUEST.fields_by_name['options'])
_RECOGNITIONREQUEST.fields_by_name['options'].containing_oneof = _RECOGNITIONREQUEST.oneofs_by_name['request']
_RECOGNITIONREQUEST.oneofs_by_name['request'].fields.append(
  _RECOGNITIONREQUEST.fields_by_name['audio_chunk'])
_RECOGNITIONREQUEST.fields_by_name['audio_chunk'].containing_oneof = _RECOGNITIONREQUEST.oneofs_by_name['request']
_RECOGNITIONRESPONSE.fields_by_name['result'].message_type = _HYPOTHESIS
_HINTS.fields_by_name['eou'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_RECOGNITIONOPTIONS.fields_by_name['audio_encoding'].enum_type = _RECOGNITIONOPTIONS_AUDIOENCODING
_RECOGNITIONOPTIONS.fields_by_name['hints'].message_type = _HINTS
_RECOGNITIONOPTIONS.fields_by_name['no_speech_timeout'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_RECOGNITIONOPTIONS.fields_by_name['max_speech_timeout'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_RECOGNITIONOPTIONS_AUDIOENCODING.containing_type = _RECOGNITIONOPTIONS
_HYPOTHESIS.fields_by_name['start'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_HYPOTHESIS.fields_by_name['end'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
DESCRIPTOR.message_types_by_name['RecognitionRequest'] = _RECOGNITIONREQUEST
DESCRIPTOR.message_types_by_name['RecognitionResponse'] = _RECOGNITIONRESPONSE
DESCRIPTOR.message_types_by_name['Hints'] = _HINTS
DESCRIPTOR.message_types_by_name['RecognitionOptions'] = _RECOGNITIONOPTIONS
DESCRIPTOR.message_types_by_name['Hypothesis'] = _HYPOTHESIS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecognitionRequest = _reflection.GeneratedProtocolMessageType('RecognitionRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONREQUEST,
  '__module__' : 'asr_pb2'
  # @@protoc_insertion_point(class_scope:smartspeech.recognition.v1.RecognitionRequest)
  })
_sym_db.RegisterMessage(RecognitionRequest)

RecognitionResponse = _reflection.GeneratedProtocolMessageType('RecognitionResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONRESPONSE,
  '__module__' : 'asr_pb2'
  # @@protoc_insertion_point(class_scope:smartspeech.recognition.v1.RecognitionResponse)
  })
_sym_db.RegisterMessage(RecognitionResponse)

Hints = _reflection.GeneratedProtocolMessageType('Hints', (_message.Message,), {
  'DESCRIPTOR' : _HINTS,
  '__module__' : 'asr_pb2'
  # @@protoc_insertion_point(class_scope:smartspeech.recognition.v1.Hints)
  })
_sym_db.RegisterMessage(Hints)

RecognitionOptions = _reflection.GeneratedProtocolMessageType('RecognitionOptions', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONOPTIONS,
  '__module__' : 'asr_pb2'
  # @@protoc_insertion_point(class_scope:smartspeech.recognition.v1.RecognitionOptions)
  })
_sym_db.RegisterMessage(RecognitionOptions)

Hypothesis = _reflection.GeneratedProtocolMessageType('Hypothesis', (_message.Message,), {
  'DESCRIPTOR' : _HYPOTHESIS,
  '__module__' : 'asr_pb2'
  # @@protoc_insertion_point(class_scope:smartspeech.recognition.v1.Hypothesis)
  })
_sym_db.RegisterMessage(Hypothesis)


DESCRIPTOR._options = None

_SMARTSPEECH = _descriptor.ServiceDescriptor(
  name='SmartSpeech',
  full_name='smartspeech.recognition.v1.SmartSpeech',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=989,
  serialized_end=1118,
  methods=[
  _descriptor.MethodDescriptor(
    name='Recognize',
    full_name='smartspeech.recognition.v1.SmartSpeech.Recognize',
    index=0,
    containing_service=None,
    input_type=_RECOGNITIONREQUEST,
    output_type=_RECOGNITIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMARTSPEECH)

DESCRIPTOR.services_by_name['SmartSpeech'] = _SMARTSPEECH

# @@protoc_insertion_point(module_scope)
